name: Create Release

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate release name
        id: release_name
        run: |
          echo "release_name=$(python3 -c <<EOF
import subprocess
import datetime

tags_process = subprocess.Popen(["git", "for-each-ref", "--sort=creatordate", "--format", "'%(refname) %(taggerdate)'", "refs/tags"], stdout=subprocess.PIPE)
tags = ""

while True:
	data = tags_process.stdout.read(1)
	if not data:
		break

	tags += data.decode("UTF-8")

for tag in reversed(tags.splitlines()):
	tag = tag[1:-2].replace("refs/tags/", "")
	if not tag.startswith("v"):
		continue

	time = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
	print(f"{tag}+{time}")
	break
EOF)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          prerelease: true
          name: Test ${{ steps.release_name.outputs.release_name }}
          tag_name: ${{ steps.release_name.outputs.release_name }}
