name: Create Release

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --tags origin
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Generate release name
        id: release_name
        run: |
          VERSION=`python3 ./.github/workflows/generate_release_version.py`
          echo "Creating release: $VERSION"
          echo "release_name=$VERSION" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          prerelease: true
          name: ${{ steps.release_name.outputs.release_name }}
          tag_name: ${{ steps.release_name.outputs.release_name }}
