name: Generate Sitemap

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  create-release:
    name: Generate Sitemap
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check if the existing sitemap is up-to-date
        id: requires_update
        run: |
          UPDATE_REQUIRED=`python3 ./.github/workflows/generate_sitemap.py -c`
          echo "Check result: $UPDATE_REQUIRED"
          echo "update_required=$UPDATE_REQUIRED" >> $GITHUB_OUTPUT
      - name: Remove existing sitemaps
        if: ${{ steps.requires_update.outputs.update_required == 'UPDATE-REQUIRED' }}
        run: rm -f sitemap.xml
      - name: Create sitemap
        if: ${{ steps.requires_update.outputs.update_required == 'UPDATE-REQUIRED' }}
        run: |
          SITEMAP=`python3 ./.github/workflows/generate_sitemap.py`
          echo "Generated sitemap:\n$SITEMAP"
          echo "$SITEMAP" >> sitemap.xml
      - name: Generate name for new branch
        if: ${{ steps.requires_update.outputs.update_required == 'UPDATE-REQUIRED' }}
        id: branch_name
        run: |
          COMMIT_HASH=`git rev-parse --short HEAD`
          echo "Latest commit short hash: $COMMIT_HASH"
          echo "branch_name=sitemaps/update-$COMMIT_HASH" >> $GITHUB_OUTPUT
      - name: Generate commit message
        if: ${{ steps.requires_update.outputs.update_required == 'UPDATE-REQUIRED' }}
        id: commit_message
        run: |
          COMMIT_HASH=`git rev-parse --short HEAD`
          echo "Latest commit short hash: $COMMIT_HASH"
          echo "commit_message=update sitemap for commit $COMMIT_HASH" >> $GITHUB_OUTPUT
      - name: Get pull request base branch
        if: ${{ steps.requires_update.outputs.update_required == 'UPDATE-REQUIRED' }}
        id: pull_base
        run: |
          CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
          echo "A pull request will be created with the base branch $CURRENT_BRANCH"
          echo "pull_base=$CURRENT_BRANCH" >> $GITHUB_OUTPUT
      - name: Create new branch and push changes
        if: ${{ steps.requires_update.outputs.update_required == 'UPDATE-REQUIRED' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: "sitemap.xml"
          new_branch: ${{ steps.branch_name.outputs.branch_name }}
          default_author: github_actions
          message: ${{ steps.commit_message.outputs.commit_message }}
      - name: Create pull request
        if: ${{ steps.requires_update.outputs.update_required == 'UPDATE-REQUIRED' }}
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ steps.branch_name.outputs.branch_name }}
          base: ${{ steps.pull_base.outputs.pull_base }}
          delete-branch: true
          title: ${{ steps.commit_message.outputs.commit_message }}
