name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run program
        run: python3 .github/workflows/css_style.py

